title:        Adam Albrecht
email:        adam.albrecht@gmail.com
markdown:     kramdown
permalink:    pretty
highlighter:  true
paginate:     5
excerpt_separator: <!-- more -->
include: [".well-known"]
